stages:
    - build
    - unit-tests
    - functional-tests

variables:
  GIT_SUBMODULE_STRATEGY: normal

build:linux:
    image: registry.videolan.org:5000/medialibrary:20190121111050
    tags:
      - debian
      - amd64
    stage: build
    script:
      - ./bootstrap
      - ./configure --enable-tests
      - make -j4
      - make -j4 check
    artifacts:
        paths:
          - unittest
          - samples
          - .libs/

unit-tests:linux:
    image: registry.videolan.org:5000/medialibrary:20190121111050
    tags:
      - debian
      - amd64
    stage: unit-tests
    dependencies:
        - build:linux
    script:
        - ./unittest

functional-tests:linux:
    image: registry.videolan.org:5000/medialibrary:20190121111050
    tags:
      - debian
      - amd64
    stage: functional-tests
    dependencies:
        - build:linux
    script:
        - ./samples -v

build:win32:
    image: registry.videolan.org:5000/medialibrary-win32:20190121122230
    tags:
      - win32
    stage: build
    script:
      - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/prefix/lib/pkgconfig"
      - ./bootstrap
      - ./configure --enable-tests --host=i686-w64-mingw32 --disable-shared
      - make -j4
      - make -j4 check
    artifacts:
        paths:
          - unittest.exe
          - samples.exe
          - .libs/

unit-tests:win32:
    image: registry.videolan.org:5000/medialibrary-win32:20190121122230
    tags:
      - win32
    stage: unit-tests
    dependencies:
        - build:win32
    script:
        - cp /prefix/dll/libvlc.dll .
        - cp /prefix/dll/libvlccore.dll .
        - ln -s /prefix/lib/vlc/plugins/ .
        - file libvlc.dll
        - file unittest.exe
        - wine unittest.exe

functional-tests:win32:
    image: registry.videolan.org:5000/medialibrary-win32:20190121122230
    tags:
      - win32
    stage: functional-tests
    dependencies:
        - build:win32
    script:
        - cp /prefix/dll/libvlc.dll .
        - cp /prefix/dll/libvlccore.dll .
        - ln -s /prefix/lib/vlc/plugins/ .
        - wine samples.exe -v

build:win64:
    image: registry.videolan.org:5000/medialibrary-win64:20190121124804
    tags:
      - win64
    stage: build
    script:
      - export PKG_CONFIG_PATH="$PKG_CONFIG_PATH:/prefix/lib/pkgconfig"
      - ./bootstrap
      - ./configure --enable-tests --host=x86_64-w64-mingw32 --disable-shared
      - make -j4
      - make -j4 check
    artifacts:
        paths:
          - unittest.exe
          - samples.exe
          - .libs/

unit-tests:win64:
    image: registry.videolan.org:5000/medialibrary-win64:20190121124804
    tags:
      - win64
    stage: unit-tests
    dependencies:
        - build:win64
    script:
        - cp /prefix/dll/libvlc.dll .
        - cp /prefix/dll/libvlccore.dll .
        - ln -s /prefix/lib/vlc/plugins/ .
        - wine unittest.exe

functional-tests:win64:
    image: registry.videolan.org:5000/medialibrary-win64:20190121124804
    tags:
      - win64
    stage: functional-tests
    dependencies:
        - build:win64
    script:
        - cp /prefix/dll/libvlc.dll .
        - cp /prefix/dll/libvlccore.dll .
        - ln -s /prefix/lib/vlc/plugins/ .
        - wine samples.exe -v
